config/routes.rb
Rails.application.routes.draw do
  namespace :donations do
    resources :registrations, only: [:new, :create]
    resources :hole_sponsors, only: [:new, :create]
    resources :lunches, only: [:new, :create]
    resources :donations, only: [:new, :create]
  end
  get "donations/hole_sponsors", to: "donations/hole_sponsors#new"
  get "donations/registrations", to: "donations/registrations#new"
  get "donations/lunches", to: "donations/lunches#new"
  get "donations/donations", to: "donations/donations#new"
  post "hook", to: "successes#hook"
  get "successes/index", to: "successes#index"
  get "successes", to: "successes#index"
  get "cancellations/index", to: "cancellations#index"
  get "cancellations", to: "cancellations#index"
  resources :donations, only: [:index]

  # Static image pages for events
  namespace :images do
    namespace :events do
      get "2023/", to: "event_images#index"
      get "2023/:id", to: "event_images#show", constraints: {id: /\d+/}
    end
  end

  get "about", to: "about#index"
  get "sponsors", to: "sponsors#index"
  get "robots.:format", to: "robots#index"

  root "welcome#index"

  post "/", to: "welcome#create"
  match "*unmatched", to: "application#route_not_found", via: :all
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:create]

  def index
  end

  def create
    render file: Rails.public_path.join("404.html"), status: :not_found, layout: false
  end
end

app/helpers/welcome_helper.rb
# frozen_string_literal: true

module WelcomeHelper
end

app/views/welcome/index.html.erb
<section id="banner">
  <h2>13<sup>th</sup> Annual Caring for Karen Sue Golf Classic</h2>
  <p>Come join us in supporting <%= current_charity.name %>.
  </p>
  <ul class="actions">
    <li><%= link_to 'Sign Up', donations_path, class: 'button special' %></li>
    <li><%= link_to 'Learn More', about_path, class: 'button special' %></li>
  </ul>
</section>
<!-- Main -->
<section id="main" class="container">
  <section class="box special">
    <header class="major">
      <h2>A Four Man Best Ball-Scramble Type Tournament</h2>
      <p>
      Come join us for competitions (like longest drive)!<br/>
      <br/>
     Golfing is optional. Lunch is after the round, followed by a raffle, and then a silent auction.
      </p>
    </header>
    <% # <span class="image featured"><%= image_tag('pic01.jpg') % ></span> %>
  </section>
  <div class="row">
    <div class="6u 12u(narrower)">
      <section class="box special">
        <span class="image featured"><%= image_tag('sponsors/applewood-golf-course.png') %></span>
        <h3><%= link_to Event.venue, Event.website, target: 'blank' %></h3>
        <p><%= Event.full_address.join('<br/>').html_safe %></p>
        <ul class="actions">
          <li><%= link_to 'Google Maps', Event.google_maps_url, target: 'blank', class: 'button alt' %></li>
        </ul>
      </section>
    </div>
    <div class="6u 12u(narrower)">
      <section class="box special">
        <span class="image featured"><%= image_tag('welcome/signup.png') %></span>
        <h3><%= Event.date %></h3>
        <p>
        <%= Event.time %></p>
        <ul class="actions">
          <li><%= link_to 'Sign Up', donations_path, class: 'button alt' %></li>
        </ul>
      </section>
    </div>
  </div>
</section>