config/routes.rb
Rails.application.routes.draw do
  namespace :donations do
    resources :registrations, only: [:new, :create]
    resources :hole_sponsors, only: [:new, :create]
    resources :lunches, only: [:new, :create]
    resources :donations, only: [:new, :create]
  end
  get "donations/hole_sponsors", to: "donations/hole_sponsors#new"
  get "donations/registrations", to: "donations/registrations#new"
  get "donations/lunches", to: "donations/lunches#new"
  get "donations/donations", to: "donations/donations#new"
  post "hook", to: "successes#hook"
  get "successes/index", to: "successes#index"
  get "successes", to: "successes#index"
  get "cancellations/index", to: "cancellations#index"
  get "cancellations", to: "cancellations#index"
  resources :donations, only: [:index]

  # Static image pages for events
  namespace :images do
    namespace :events do
      get "2023/", to: "event_images#index"
      get "2023/:id", to: "event_images#show", constraints: {id: /\d+/}
    end
  end

  get "about", to: "about#index"
  get "sponsors", to: "sponsors#index"
  get "robots.:format", to: "robots#index"

  root "welcome#index"

  post "/", to: "welcome#create"
  match "*unmatched", to: "application#route_not_found", via: :all
end

app/models/event.rb
# frozen_string_literal: true

class Event
  class << self
    def venue
      "Applewood Golf Course"
    end

    def full_address
      [
        address,
        "#{city}, #{state} #{zip}"
      ]
    end

    def date
      "Saturday, September 20th, 2025"
    end

    def time
      "7:30am Shotgun Start"
    end

    def check_deadline
      "Wednesday, September 9th, 2025"
    end

    def iteration
      "13th"
    end

    def google_maps_url
      "https://maps.google.com/maps?q=Applewood+Golf+Course,+W+32nd+Ave,+Golden,+CO&hl=en&ll=39.76489,-105.156605&spn=0.010177,0.020084&sll=39.762611,-105.157246&sspn=0.010177,0.020084&oq=apple14001+W+32nd+Ave,+Golden,+CO&t=m&z=16&iwloc=A"
    end

    def website
      "https://www.applewoodgc.com/"
    end

    private

    def address
      "14001 W. 32nd Avenue"
    end

    def city
      "Golden"
    end

    def state
      "CO"
    end

    def zip
      "80401"
    end
  end
end

app/models/event_image.rb
# frozen_string_literal: true

class EventImage
  EVENT_ID = "2023"
  IMAGE_RANGE = 1..173
  PARENT_DIR = "2023-event"
  TYPE_DIRS = {
    thumb: "thumbs",
    original: "originals",
    preview: "previews",
    resized: "resized"
  }

  TALL_IDS = [1, 2, 3, 4, 5, 6, 9, 10, 11, 12, 13, 14, 15, 18, 20, 21,
    22, 36, 37, 38, 42, 43, 44, 45, 57, 58, 59, 60, 61, 62,
    63, 64, 67, 68, 70, 71, 72, 75, 76, 77, 78, 79, 84, 86,
    88, 89, 90, 92, 93, 104, 105, 106, 107, 108, 114, 115,
    116, 117, 118, 120, 121, 122, 24, 128, 133, 134, 142,
    143, 144, 145, 146, 147, 148, 149, 152, 153, 154, 155,
    156, 157, 159, 160, 161, 166, 169, 170, 171, 173]

  class NotFoundError < StandardError; end

  attr_reader :id

  def initialize(id)
    @id = id
  end

  def anchor_id
    "event-image-#{EVENT_ID}-#{padded_id}"
  end

  def self.find(id)
    return unless IMAGE_RANGE.include? id

    new(id)
  end

  def self.find!(id)
    raise NotFoundError, "Invalid EventImage ID (#{id})" unless IMAGE_RANGE.include? id

    new(id)
  end

  def self.all
    IMAGE_RANGE.map { |id| new(id) }
  end

  def thumb_url
    return unless valid?

    url type: :thumb
  end

  def original_url
    return unless valid?

    url type: :original
  end

  def preview_url
    return unless valid?

    url type: :preview
  end

  def resized_url
    return unless valid?

    url type: :resized
  end

  def valid?
    IMAGE_RANGE.include? @id
  end

  def thumb_width
    return 133 if tall?

    200
  end

  def thumb_height
    return 200 if tall?

    133
  end

  private

  def tall?
    TALL_IDS.include? @id
  end

  def padded_id
    "0" * (3 - @id.to_s.size) + @id.to_s
  end

  def url(type:)
    "#{domain}/#{PARENT_DIR}/#{TYPE_DIRS.fetch(type)}/#{padded_id}.jpg"
  end

  def domain
    ENV.fetch("IMAGE_HOST_URL", "http://localhost")
  end
end

app/controllers/images/events/event_images_controller.rb
# frozen_string_literal: true

class Images::Events::EventImagesController < ApplicationController # /index/events/2023
  rescue_from EventImage::NotFoundError, with: :image_not_found

  def index
    @images = EventImage.all
  end

  def show
    @image = EventImage.find! params[:id].to_i
  end

  private

  def image_not_found
    @error_message = "Sorry, we're unable to find that image. Please try again."
    @images = EventImage.all

    render :index
  end
end

app/views/images/events/event_images/_error.html.erb
<div>
  <section class="box special" style="color:darkorange;font-weight:bold;">
    <%= @error_message %>
  </section>
</div>

app/views/images/events/event_images/_image.html.erb
<div class="4u 12u(narrower)">
  <section class="box special">
    <a id="<%= image.anchor_id %>"></a>
    <%= link_to image_tag(image.thumb_url, loading: 'lazy', size: "#{image.thumb_width}x#{image.thumb_height}"), images_events_path(image.id) %>
  </section>
</div>

app/views/images/events/event_images/index.html.erb
<section id="main" class="container">
  <section class="box special">
    <header class="major">
      <h2>2023 Event Pictures</h2>
    </header>
  </section>
  <%= render partial: "error", locals: { error_message: @error_message } if @error_message %>
  <% if @images.any? %>
    <% x = 0 %>
    <% @images.each do |image| %>
      <% if x % 3 == 0 %>
        <div class="row">
      <% end %>
      <%= render partial: "image", locals: { image: image} %>
      <% x += 1 %>
      <% if x % 3 == 0 %>
        </div>
      <% end %>
    <% end %>
    <% if x % 3 != 0 %>
      </div>
    <% end %>
  <% end %>
</section>

app/views/images/events/event_images/show.html.erb
<section id="main" class="container">
  <div class="box" align="center">
    <h3>2023 Event Picture #<%= @image.id %> - <%= link_to "Back", "#{images_events_2023_path}\##{@image.anchor_id}" %></h3>
    <p>
      <picture>
        <source media="(max-width: 799px)" srcset="<%= @image.preview_url %>" />
        <source media="(min-width: 800px)" srcset="<%= @image.resized_url %>" />
        <img src="<%= @image.resized_url %>" alt="2023 Event - Image #<%= @image.id %>" />
      </picture>

      <ul class="actions">
        <li><a href="<%= @image.original_url %>" class="button alt" target="_blank">Download Original</a></li>
      </ul>
    </p>
  </div>
</section>